---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

Grant
`Question 1: ` There are many variables including: Address, Occupancy, Price, YearBuilt, and Bedrooms. There are number, character, date type of variables in the dataset. The address gives the address of the house, the occupancy gives the number of people that can live in the house, the price lists the last price the home sold at, the YearBuilt gives the year that house was built, and bedrooms lists the number of bedrooms in the house. The range of the Sale Price data is between 0 and 20,500,000.


Grant
`Question 2: ` The Price and Sale Date variable have a special focus for this project since we are looking at the historic residential sales of houses in Ames since 2017.


Grant
`Question 3: ` 
